name: Build

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build image
        run: docker build -t proxy .
