name: Push-Dev

on:
 push:
   branches:
     - master

jobs:
  Build And Push Dev:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: docker build -t proxy .
      - name: Push to ECR
        run: |
          #apt-get install python3
          pip3 install awscli
          $(aws ecr get-login-password)
          docker tag proxy:latest $ECR_REPO:dev
          docker push $ECR_REPO:dev
