name: Push-Release

on:  
  push:
    tags:
      - '^*-release$'

jobs:
  Build-And-Push-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get the version
        id: get_version
        run: |
          version=${GITHUB_REF/refs\/tags\//}
          version_without_release=$(echo $version | sed 's/-release//')
          echo ::set-output name=VERSION::${version_without_release}
      - name: Build image
        run: docker build -t proxy .
      - name: Push to ECR
        run: |
          pip3 install awscli
          $(aws ecr get-login-password)

          TAGGED_ECR_REPO=${ECR_REPO}:${{ steps.previous_version.outputs.version }}
          # tag and push to the version
          docker tag proxy:latest $TAGGED_ECR_REPO
          docker push $TAGGED_ECR_REPO
          # also tag and push to latest
          docker tag $TAGGED_ECR_REPO $ECR_REPO:latest
          docker push $ECR_REPO:latest
